export const LOAD_PLAYERS_RUSHING = 'NFLRushingApp/App/LOAD_PLAYERS_RUSHING';
export const LOAD_PLAYERS_RUSHING_SUCCESS = 'NFLRushingApp/App/LOAD_PLAYERS_RUSHING_SUCCESS';
export const LOAD_PLAYERS_RUSHING_ERROR = 'NFLRushingApp/App/LOAD_PLAYERS_RUSHING_ERROR';
